import streamlit as st
import pandas as pd
import database_manager as db
from fpdf import FPDF
from io import BytesIO
from datetime import datetime

# --- CUSTOM CSS FOR MKCE MATRIX ---
st.markdown("""
<style>
    .tt-header { text-align: center; color: #1e3a8a; margin-bottom: 20px; }
    .tt-container { overflow-x: auto; padding: 15px; background: #ffffff; border-radius: 12px; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); }
    .mkce-table { 
        width: 100%; 
        border-collapse: separate; 
        border-spacing: 0; 
        border: 1px solid #e2e8f0; 
        border-radius: 12px; 
        overflow: hidden; 
        table-layout: fixed; 
        min-width: 1000px;
        font-family: 'Inter', system-ui, -apple-system, sans-serif;
    }
    .mkce-table th { background: #f8fafc; color: #1e293b; font-weight: 700; padding: 12px; border: 1px solid #e2e8f0; font-size: 0.8rem; text-align: center; }
    .mkce-table td { padding: 8px; border: 1px solid #e2e8f0; text-align: center; vertical-align: middle; position: relative; height: 110px; }
    .day-cell { background: #f1f5f9; font-weight: 800; color: #475569; width: 100px; font-size: 0.85rem; }
    .break-cell { 
        background: #fff7ed; 
        color: #c2410c; 
        font-weight: 700; 
        font-size: 0.6rem; 
        width: 50px; 
        writing-mode: vertical-lr; 
        text-orientation: mixed;
        border: 1px solid #fdba7440;
    }
    .subject-box { padding: 4px 8px; border-radius: 6px; font-weight: 700; font-size: 0.85rem; margin-bottom: 4px; border-bottom: 1px solid #f1f5f9; }
    .teacher-box { font-size: 0.75rem; color: #64748b; font-weight: 500; }
    .proxy-badge { border-radius: 4px; padding: 1px 4px; font-weight: 800; margin-top: 4px; display: inline-block; font-size: 0.55rem; }
    
    .sub-aiml { background: #eff6ff; color: #1d4ed8; border: 1px solid #bfdbfe; }
    .sub-dbms { background: #f5f3ff; color: #6d28d9; border: 1px solid #ddd6fe; }
    .sub-adm { background: #ecfdf5; color: #047857; border: 1px solid #a7f3d0; }
    .lab-subject { background: #fff1f2; color: #be123c; border: 1px solid #fecdd3; }
    .elective-subject { background: #fffbeb; color: #b45309; border: 1px solid #fde68a; }
    .absent-subject { border-left: 4px solid #f43f5e !important; opacity: 0.9; }
</style>
""", unsafe_allow_html=True)

# --- HEADER ---
st.markdown("""
    <div class='tt-header'>
        <h2 style='margin:0;'>M.KUMARASAMY COLLEGE OF ENGINEERING (Autonomous)</h2>
        <p style='margin:5px 0;'>Department of Computer Science and Engineering</p>
        <h4 style='margin:0; color: #64748b;'>CLASS TIME TABLE - II YEAR IV SEM</h4>
    </div>
""", unsafe_allow_html=True)

# --- PDF ENGINE ---
def create_pdf_buffer(subject, plan):
    pdf = FPDF()
    pdf.add_page()
    
    # Border & Background (Light tint)
    pdf.set_fill_color(248, 250, 252)
    pdf.rect(5, 5, 200, 287, 'DF')
    pdf.set_draw_color(37, 99, 235)
    pdf.rect(7, 7, 196, 283) 

    # Header
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(190, 15, "M. KUMARASAMY COLLEGE OF ENGINEERING (Autonomous)", ln=True, align="C")
    
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(190, 10, "AI PROXY HUB: LESSON CONTINUITY PLAN", ln=True, align="C")
    pdf.ln(5)
    
    # Subject Banner
    pdf.set_fill_color(37, 99, 235)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(190, 12, f" SUBJECT: {subject.upper()} ", ln=True, align="C", fill=True)
    pdf.ln(10)

    # Content
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(190, 10, "1. Executive Summary / Learning Objectives", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(180, 8, plan['summary'].encode('ascii', 'ignore').decode('ascii'))
    
    pdf.ln(10)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(190, 10, "2. Verification Quiz (Post-Session Assessment)", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for i, q in enumerate(plan['quiz'], 1):
        pdf.multi_cell(180, 8, f"{i}. {q.encode('ascii', 'ignore').decode('ascii')}")
    
    pdf.ln(15)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(190, 10, f"Generated by MKCE Smart Classroom AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align="C")
    
    pdf_content = pdf.output()
    return BytesIO(pdf_content)

# --- DATA ---
conn = db.get_connection()
teachers_df = pd.read_sql_query("SELECT id, name, specialty, status FROM teachers", conn)
conn.close()
timetable_data = db.get_timetable()

# --- SIDEBAR ---
if st.session_state.role == "Admin":
    st.sidebar.subheader("⚙️ AI Schedule Control")
    if st.sidebar.button("🚀 Run AI IV-SEM Scheduler"):
        if db.generate_smart_timetable():
            st.success("Matrix Generated!")
            st.rerun()
    if st.sidebar.button("🧹 Clear Proxy Cache"):
        st.session_state.locked_proxies = {}
        st.rerun()
    st.sidebar.markdown("---")
    st.sidebar.subheader("📢 Absence Simulation")
    staff_to_mark = st.sidebar.selectbox("Select Staff", teachers_df['name'])
    status_to_set = st.sidebar.radio("Set Status", ["Available", "Absent"])
    if st.sidebar.button("Update Status"):
        db.mark_teacher_status(staff_to_mark, status_to_set)
        st.session_state.locked_proxies = {}
        st.success("Applied!")
        st.rerun()

# --- MATRIX RENDERING ---
if not timetable_data:
    st.info("No Data. Click 'Run Scheduler'.")
else:
    days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
    periods = ["I", "II", "III", "IV", "V", "VI", "VII"]
    times = ["8:45-9:45", "9:45-10:45", "11:05-12:05", "12:05-12:55", "1:45-2:45", "3:00-3:50", "3:50-4:40"]
    
    if "locked_proxies" not in st.session_state: st.session_state.locked_proxies = {}
    
    cur_sim_day = st.session_state.get('sim_day', 'Monday')
    if "last_sim_day" not in st.session_state: st.session_state.last_sim_day = cur_sim_day
    if st.session_state.last_sim_day != cur_sim_day:
        st.session_state.locked_proxies = {}
        st.session_state.last_sim_day = cur_sim_day

    html = "<div class='tt-container'><table class='mkce-table'>"
    html += "<tr><th>Day / Time</th>"
    for i, p in enumerate(periods):
        if i == 2: html += "<th class='break-cell'>BREAK</th>"
        if i == 4: html += "<th class='break-cell'>LUNCH</th>"
        if i == 5: html += "<th class='break-cell'>BREAK</th>"
        html += f"<th>{p}<small><br>{times[i]}</small></th>"
    html += "</tr>"

    unique_hub_records = {}
    for day in days:
        html += f"<tr><td class='day-cell'>{day}</td>"
        day_rows = [r for r in timetable_data if r[0] == day]
        day_assigned_proxies = []
        skip_next = False
        
        for i, p in enumerate(periods):
            # IMPORTANT: Separators must ALWAYS be rendered, even if skip_next is true
            # This ensures the structural column count (11) is never broken.
            if i == 2: html += "<td class='break-cell'>BREAK</td>"
            if i == 4: html += "<td class='break-cell'>LUNCH</td>"
            if i == 5: html += "<td class='break-cell'>BREAK</td>"

            if skip_next:
                skip_next = False
                continue

            p_data = next((r for r in day_rows if r[1] == p), None)
            colspan = 1
            if i < len(periods) - 1:
                next_p = periods[i+1]
                can_merge = (i in [0, 2, 5]) 
                if can_merge:
                    next_p_data = next((r for r in day_rows if r[1] == next_p), None)
                    if p_data and next_p_data and p_data[2] == next_p_data[2]:
                        colspan = 2
                        skip_next = True

            if p_data:
                _, _, subject, t_name, specialty = p_data
                t_row = teachers_df[teachers_df['name'] == t_name]
                status = t_row['status'].values[0] if not t_row.empty else "Available"
                is_proxy_needed = (status == "Absent" and day == cur_sim_day)
                is_lab = "LAB" in subject
                is_elective = any(kw in subject for kw in ["CSD", "EDA", "PQST"])
                sub_class = "lab-subject" if is_lab else ("elective-subject" if is_elective else "")
                if not sub_class:
                    if "AIML" in subject: sub_class = "sub-aiml"
                    elif "DBMS" in subject: sub_class = "sub-dbms"
                    elif "ADM" in subject: sub_class = "sub-adm"

                if is_proxy_needed:
                    cache_key = (day, p)
                    subj_key = f"SUBJ_{day}_{subject}"
                    if cache_key not in st.session_state.locked_proxies:
                        if subj_key in st.session_state.locked_proxies:
                            st.session_state.locked_proxies[cache_key] = st.session_state.locked_proxies[subj_key]
                        else:
                            sub_raw = db.get_available_substitute(specialty or "General", day, p, exclude_names=day_assigned_proxies)
                            sub_name = sub_raw.replace("Proxy: ", "").replace("Substitute: ", "")
                            st.session_state.locked_proxies[cache_key] = sub_name
                            st.session_state.locked_proxies[subj_key] = sub_name
                    
                    sub_name = st.session_state.locked_proxies[cache_key]
                    day_assigned_proxies.append(sub_name)
                    sub_row = teachers_df[teachers_df['name'] == sub_name]
                    sub_spec = str(sub_row['specialty'].values[0]) if not sub_row.empty else "General"
                    match_spec = str(specialty or "General")
                    
                    # Refined matching logic (Includes shared category expertise: AIML/DBMS and PQST/EDA)
                    is_specialist = False
                    sub_s = sub_spec.upper()
                    mat_s = match_spec.upper()
                    
                    if "GENERAL" not in sub_s and "GENERAL" not in mat_s:
                        if sub_s in mat_s or mat_s in sub_s:
                            is_specialist = True
                        shared_map = {'AIML': 'DBMS', 'DBMS': 'AIML', 'PQST': 'EDA', 'EDA': 'PQST'}
                        if shared_map.get(sub_s) == mat_s:
                            is_specialist = True
                    elif sub_s == mat_s and mat_s != "GENERAL":
                        is_specialist = True

                    tag = "Specialist Proxy" if is_specialist else "General Substitute"
                    icon = "🧠" if is_specialist else "🛠️"
                    clr = "#4338ca" if is_specialist else "#64748b"

                    if f"{day}_{subject}" not in unique_hub_records:
                        unique_hub_records[f"{day}_{subject}"] = {'subject': subject, 'teacher': t_name, 'sub': sub_name, 'day': day, 'type': tag}

                    html += f"<td colspan='{colspan}'>"
                    html += f"<div class='subject-box absent-subject {sub_class}'>{subject}</div>"
                    html += f"<div class='proxy-badge' style='background: {clr}15; color: {clr}; border: 1px solid {clr}40;'>{icon} {tag}</div>"
                    html += f"<div class='teacher-box' style='color: #10b981; font-weight: 600;'>📍 {sub_name}</div>"
                    html += "</td>"
                else:
                    html += f"<td colspan='{colspan}'><div class='subject-box {sub_class}'>{subject}</div><div class='teacher-box'>{t_name}</div></td>"
            else:
                # PLACEHOLDER FOR STABILITY
                html += f"<td colspan='{colspan}' style='background: #f9fafb; border: 1px dashed #e2e8f0;'><div style='color:#cbd5e1; font-style: italic; font-size: 0.7rem;'>-</div></td>"
        html += "</tr>"
    html += "</table></div>"
    st.markdown(html, unsafe_allow_html=True)

    # --- ANALYSIS BOARD ---
    if unique_hub_records and st.session_state.role != "Student":
        st.markdown("---")
        st.markdown("### 📊 AI Proxy Analysis Board")
        specs = [r for r in unique_hub_records.values() if "Specialist" in r['type']]
        gens = [r for r in unique_hub_records.values() if "General" in r['type']]
        a_col1, a_col2 = st.columns(2)
        with a_col1:
            st.markdown("<div style='background: #eef2ff; padding: 10px; border-radius: 10px;'><div style='color: #4338ca; font-weight: 800;'>🧠 ACADEMIC CONTINUITY</div></div>", unsafe_allow_html=True)
            for r in specs: st.markdown(f"✅ **{r['subject']}** ← 📍 **{r['sub']}**")
        with a_col2:
            st.markdown("<div style='background: #f8fafc; padding: 10px; border-radius: 10px;'><div style='color: #475569; font-weight: 800;'>🛠️ OPERATIONAL SUPPORT</div></div>", unsafe_allow_html=True)
            for r in gens: st.markdown(f"◽ **{r['subject']}** ← 📍 **{r['sub']}**")

    # --- HUB SECTION ---
    if unique_hub_records and st.session_state.role != "Student":
        st.markdown("<br>", unsafe_allow_html=True)
        st.subheader("📥 AI Lesson Proxy Hub")
        for hub_key, rec in unique_hub_records.items():
            plan = db.get_lesson_plan(rec['subject'].replace(" LAB", "").split(" (")[0])
            with st.expander(f"📖 {rec['subject']} Strategy ({rec['day']})"):
                st.markdown(f"**{rec['type']}**: 📍 **{rec['sub']}**")
                st.info(plan['summary'])
                pdf_bytes = create_pdf_buffer(rec['subject'], plan)
                if pdf_bytes:
                    st.download_button(label=f"Download {rec['subject']} Plan", data=pdf_bytes, file_name=f"Plan_{rec['subject']}.pdf", mime="application/pdf", key=f"dl_{hub_key}")
